version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # External services port range
    environment:
      - SERVICES=s3,kinesis # Enable S3 and Kinesis (for Kafka emulation)
      - DEBUG=1
      - KINESIS_PROVIDER=kinesis-mock # Use Kinesis mock for Kafka emulation
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"

  zookeeper:
    container_name: "zookeeper"
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: "kafka"
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - "./kafka-data:/var/lib/kafka/data" # Persist Kafka data
    depends_on:
      - zookeeper

  clickhouse:
    container_name: "clickhouse"
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native protocol
    volumes:
      - "./clickhouse-data:/var/lib/clickhouse" # Persist ClickHouse data